name: AWS Terraform integration using github actions 

on:
  push:
    branches:
    - main

jobs:
  terrafromconfigre:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: insttaling and configure aws cli 
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name:  aws configure 
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]
          aws_access_key_id = 
          aws_secret_access_key = " > ~/.aws/credentials
          

        

